# Generated by Django 4.2.5 on 2023-10-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_habits_time_alter_habits_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='frequency',
            field=models.CharField(choices=[('one daily', 'Ежедневно'), ('two daily', 'Раз в два дня'), ('three daily', 'Раз в три дня'), ('four daily', 'Раз в четыре дня'), ('five daily', 'Раз в пять дней'), ('six daily', 'Раз в шесть дней'), ('seven daily', 'Раз в семь дней')], default='Ежедневно', max_length=100, verbose_name='периодичность'),
        ),
    ]
